version: '3.7'

services:
  app:
    build: .
    command: npm run dev
    restart: always
    depends_on:
      - db
      - db-testing
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3333:3333
    environment:
      - NODE_ENV=development
      - PORT=3333
      - PG_CONNECTION=postgresql://postgres:password@db:5432/postgres
      - PG_CONNECTION_TESTING=postgresql://postgres:password@db-testing:5432/postgres
  db:
    image: postgres:14.1
    restart: always
    ports:
      - 4444:5432
    environment:
      - POSTGRES_PASSWORD=password
  db-testing:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
